-- Python Submit : stockage du code des exercices élèves
-- À exécuter dans Supabase > SQL Editor avant de tester la sauvegarde du code.

create table if not exists public.student_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  student_name text not null,
  class_name text not null,
  exercise_id text not null,
  code text not null default '',
  validated boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (user_id, exercise_id)
);

alter table public.student_submissions enable row level security;

-- Un élève ne lit que ses propres travaux.
drop policy if exists "students_read_own_submissions" on public.student_submissions;
create policy "students_read_own_submissions"
on public.student_submissions for select
to authenticated
using (auth.uid() = user_id);

-- Un élève ne crée que ses propres travaux.
drop policy if exists "students_insert_own_submissions" on public.student_submissions;
create policy "students_insert_own_submissions"
on public.student_submissions for insert
to authenticated
with check (auth.uid() = user_id);

-- Un élève ne modifie que ses propres travaux.
drop policy if exists "students_update_own_submissions" on public.student_submissions;
create policy "students_update_own_submissions"
on public.student_submissions for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create index if not exists student_submissions_user_idx on public.student_submissions(user_id);
create index if not exists student_submissions_class_idx on public.student_submissions(class_name);
