// Charge la synchronisation Supabase sans modifier eleve.html.
(() => { const s=document.createElement('script'); s.src='supabase-sync.js'; document.head.appendChild(s); })();

// Catalogue autonome des exercices — aucune dépendance à Render.
window.PYTHON_EXERCISES = [
  {id:'tp1q1',tp:'TP1',title:'Q1 — Loi d’Ohm',description:'Contexte : loi d’Ohm — U = R × I\n\nDéclarer R = 470 et I = 0.02, calculer la tension U = R * I et l’afficher.\nVérifier que U = 9.4 V.\n\nSortie attendue :\nTension U = 9.4 V',tests:[{expected:'Tension U = 9.4 V'}]},
  {id:'tp1q2',tp:'TP1',title:'Q2 — Types de données',description:'Utiliser type() pour afficher le type de R = 470, I = 0.02 et d’une variable nom = "Résistance".\n\nSortie attendue :\n<class \'int\'>\n<class \'float\'>\n<class \'str\'>',tests:[{expected:"<class 'int'>\n<class 'float'>\n<class 'str'>"}]},
  {id:'tp1q3',tp:'TP1',title:'Q3 — Entrées utilisateur',description:'Demander R et I à l’utilisateur avec input(), les convertir en float(), calculer U = R * I et l’afficher.\n\nTest : R=470 et I=0.02.\nSortie attendue :\nTension U = 9.4 V',tests:[{inputs:['470','0.02'],expected:'Tension U = 9.4 V'}]},
  {id:'tp1q4',tp:'TP1',title:'Q4 — Puissance',description:'Avec R = 470 et I = 0.02, calculer U = R * I puis P = U * I.\nAfficher P arrondi à 4 décimales avec l’unité watts.\n\nSortie attendue :\nPuissance P = 0.188 watts',tests:[{expected:'Puissance P = 0.188 watts'}]},
  {id:'tp1q5',tp:'TP1',title:'Q5 — Résumé avec f-string',description:'Avec R = 470, I = 0.02, U = R * I et P = U * I, afficher un résumé complet avec une f-string.\n\nSortie attendue :\nR = 470 Ω | I = 0.02 A | U = 9.4 V | P = 0.188 W',tests:[{expected:'R = 470 Ω | I = 0.02 A | U = 9.4 V | P = 0.188 W'}]},
  {id:'tp2q1',tp:'TP2',title:'Q1 — LED',description:'Une LED est passante si U > 2.0 V. Demander U à l’utilisateur et afficher "LED allumée" ou "LED éteinte".',tests:[{inputs:['3.0'],expected:'LED allumée'},{inputs:['1.5'],expected:'LED éteinte'}]},
  {id:'tp2q2',tp:'TP2',title:'Q2 — Seuils de tension',description:'Classifier la tension avec if/elif/else :\n- faible si U < 4.5 V\n- nominale si 4.5 <= U <= 5.5 V\n- élevée si U > 5.5 V\n\nDemander U avec input().',tests:[{inputs:['4.0'],expected:'Tension faible'},{inputs:['5.0'],expected:'Tension nominale'},{inputs:['6.0'],expected:'Tension élevée'}]},
  {id:'tp2q3',tp:'TP2',title:'Q3 — Condition AND',description:'Un système se déclenche si U > 12 V ET I > 2 A. Tester directement dans le code :\nU=15, I=3 ; U=10, I=3 ; U=15, I=1.\n\nSortie attendue :\nU=15 I=3 : Système déclenché\nU=10 I=3 : Système non déclenché\nU=15 I=1 : Système non déclenché',tests:[{expected:'U=15 I=3 : Système déclenché\nU=10 I=3 : Système non déclenché\nU=15 I=1 : Système non déclenché'}]},
  {id:'tp2q4',tp:'TP2',title:'Q4 — Table de vérité AND',description:'Afficher la table de vérité d’une porte AND pour A, B dans {0, 1} avec deux boucles for imbriquées.\n\nSortie attendue :\nA=0 B=0 : 0\nA=0 B=1 : 0\nA=1 B=0 : 0\nA=1 B=1 : 1',tests:[{expected:'A=0 B=0 : 0\nA=0 B=1 : 0\nA=1 B=0 : 0\nA=1 B=1 : 1'}]},
  {id:'tp2q5',tp:'TP2',title:'Q5 — Thermostat',description:'Thermostat :\n- T > 22°C : "Chauffage coupé"\n- T < 18°C : "Chauffage allumé"\n- sinon : "Maintien"\n\nDemander T avec input().',tests:[{inputs:['25'],expected:'Chauffage coupé'},{inputs:['15'],expected:'Chauffage allumé'},{inputs:['20'],expected:'Maintien'}]},
  {id:'tp3q1',tp:'TP3',title:'Q1 — Capital placé',description:'Un capital de 20 000 € est placé à 6 % par an. Avec une boucle for, afficher le capital à la fin de chacune des 20 premières années, arrondi à l’unité.\n\nDébut attendu :\nAnnée 1 : 21200 €\nAnnée 2 : 22472 €',tests:[]},
  {id:'tp3q2',tp:'TP3',title:'Q2 — Boucle while',description:'Avec une boucle while, diviser U = 100 V par 2 à chaque tour jusqu’à ce que U < 1 V. Afficher le nombre d’itérations nécessaires.',tests:[]},
  {id:'tp3q3',tp:'TP3',title:'Q3 — Somme de 1 à 200',description:'Avec une boucle for, calculer la somme 1 + 2 + ... + 200. Vérifier le résultat avec n*(n+1)//2 et afficher les deux valeurs.',tests:[]},
  {id:'tp3q4',tp:'TP3',title:'Q4 — Jeu de dés',description:'Simuler un jeu de dés avec une boucle while. À chaque tour, lancer deux dés avec random.randint(1, 6). S’arrêter dès qu’un double est obtenu et afficher le nombre de lancers nécessaires.',tests:[]},
  {id:'tp3q5',tp:'TP3',title:'Q5 — Table de multiplication',description:'Afficher une table de multiplication de 1 à 5 avec deux boucles for imbriquées. Aligner les colonnes avec le format :>4d.',tests:[]}
,
  {id:'tp4q1',tp:'TP4',title:'Q1 — Fonction tension',description:'Écrire une fonction tension(R, I) qui retourne U = R * I. Afficher tension(470, 0.02).\n\nSortie attendue :\n9.4',tests:[{expected:'9.4'}]},
  {id:'tp4q2',tp:'TP4',title:'Q2 — Fonction puissance',description:'Écrire une fonction puissance(U, I) qui retourne P = U * I. Afficher puissance(12, 2.5).\n\nSortie attendue :\n30.0',tests:[{expected:'30.0'}]},
  {id:'tp4q3',tp:'TP4',title:'Q3 — Conversion mV → V',description:'Écrire une fonction mv_vers_v(mv) qui convertit des millivolts en volts. Afficher la conversion de 3300 mV.\n\nSortie attendue :\n3.3 V',tests:[{expected:'3.3 V'}]},
  {id:'tp4q4',tp:'TP4',title:'Q4 — État d’une tension',description:'Écrire une fonction etat(U) qui retourne "faible" si U < 4.5, "nominale" si U <= 5.5, sinon "élevée". Tester avec 4.0, 5.0 et 6.0.',tests:[{expected:'faible\nnominale\nélevée'}]},
  {id:'tp4q5',tp:'TP4',title:'Q5 — Bilan électrique',description:'Créer une fonction bilan(R, I) qui calcule U et P puis retourne une chaîne : "U = ... V | P = ... W". Tester avec R=470 et I=0.02.\n\nSortie attendue :\nU = 9.4 V | P = 0.188 W',tests:[{expected:'U = 9.4 V | P = 0.188 W'}]},

  {id:'tp5q1',tp:'TP5',title:'Q1 — Série de tensions',description:'Avec mesures = [4.8, 5.1, 5.0, 6.2, 4.9, 5.2], afficher le nombre de mesures.\n\nSortie attendue :\n6 mesures',tests:[{expected:'6 mesures'}]},
  {id:'tp5q2',tp:'TP5',title:'Q2 — Minimum et maximum',description:'Avec mesures = [4.8, 5.1, 5.0, 6.2, 4.9, 5.2], afficher la valeur minimale puis la valeur maximale.\n\nSortie attendue :\nMin = 4.8 V\nMax = 6.2 V',tests:[{expected:'Min = 4.8 V\nMax = 6.2 V'}]},
  {id:'tp5q3',tp:'TP5',title:'Q3 — Tension moyenne',description:'Calculer la moyenne de mesures = [4.8, 5.1, 5.0, 6.2, 4.9, 5.2] avec sum() et len(). Afficher le résultat arrondi à 2 décimales.\n\nSortie attendue :\nMoyenne = 5.2 V',tests:[{expected:'Moyenne = 5.2 V'}]},
  {id:'tp5q4',tp:'TP5',title:'Q4 — Dépassements de seuil',description:'Compter dans [4.8, 5.1, 5.0, 6.2, 4.9, 5.2] les mesures strictement supérieures à 5.5 V.\n\nSortie attendue :\n1 dépassement',tests:[{expected:'1 dépassement'}]},
  {id:'tp5q5',tp:'TP5',title:'Q5 — Surveillance complète',description:'Pour mesures = [4.8, 5.1, 5.0, 6.2, 4.9, 5.2], afficher min, max, moyenne arrondie à 2 décimales et "ALERTE" si au moins une valeur dépasse 6 V.\n\nSortie attendue :\nMin = 4.8 V\nMax = 6.2 V\nMoyenne = 5.2 V\nALERTE',tests:[{expected:'Min = 4.8 V\nMax = 6.2 V\nMoyenne = 5.2 V\nALERTE'}]},

  {id:'tp6q1',tp:'TP6',title:'Q1 — Découper une trame',description:'On reçoit la trame "TEMP:21.5". Utiliser split(":") pour afficher séparément le nom du capteur et sa valeur.\n\nSortie attendue :\nCapteur = TEMP\nValeur = 21.5',tests:[{expected:'Capteur = TEMP\nValeur = 21.5'}]},
  {id:'tp6q2',tp:'TP6',title:'Q2 — Convertir une donnée',description:'À partir de trame = "U:5.25", extraire la valeur, la convertir en float puis afficher son double.\n\nSortie attendue :\n10.5',tests:[{expected:'10.5'}]},
  {id:'tp6q3',tp:'TP6',title:'Q3 — Plusieurs champs',description:'Découper la trame "TEMP=23.4;HUM=48" en champs puis afficher :\nTempérature = 23.4 °C\nHumidité = 48 %',tests:[{expected:'Température = 23.4 °C\nHumidité = 48 %'}]},
  {id:'tp6q4',tp:'TP6',title:'Q4 — Construire une trame',description:'Avec capteur="U", valeur=5.1 et unite="V", construire avec une f-string la trame "U;5.1;V" et l’afficher.',tests:[{expected:'U;5.1;V'}]},
  {id:'tp6q5',tp:'TP6',title:'Q5 — Vérifier une trame',description:'Pour trame="TEMP:28.5", extraire la température et afficher "ALERTE TEMP" si elle dépasse 25 °C, sinon "TEMP OK".',tests:[{expected:'ALERTE TEMP'}]},

  {id:'tp7q1',tp:'TP7',title:'Q1 — Compter les anomalies',description:'Dans [5.0, 5.1, 7.2, 4.9, 6.8, 5.0], compter les valeurs supérieures à 6 V.\n\nSortie attendue :\n2 anomalies',tests:[{expected:'2 anomalies'}]},
  {id:'tp7q2',tp:'TP7',title:'Q2 — Rechercher une valeur',description:'Dans [18, 19, 22, 27, 21], rechercher si une température supérieure à 25 °C existe. Afficher "Surchauffe détectée" ou "Aucune surchauffe".',tests:[{expected:'Surchauffe détectée'}]},
  {id:'tp7q3',tp:'TP7',title:'Q3 — Indice de l’anomalie',description:'Dans [5.0, 5.1, 7.2, 4.9], afficher l’indice de la première valeur supérieure à 6 V.\n\nSortie attendue :\nIndice = 2',tests:[{expected:'Indice = 2'}]},
  {id:'tp7q4',tp:'TP7',title:'Q4 — Classer des mesures',description:'Pour [3.8, 5.0, 5.4, 6.1], afficher pour chaque valeur : "faible" si <4.5, "OK" entre 4.5 et 5.5 inclus, sinon "élevée". Afficher seulement les quatre états, un par ligne.',tests:[{expected:'faible\nOK\nOK\nélevée'}]},
  {id:'tp7q5',tp:'TP7',title:'Q5 — Diagnostic',description:'Pour mesures=[5.0, 5.2, 6.4, 6.8, 5.1], compter les valeurs >6. Si le nombre est au moins 2 afficher "PANNE PROBABLE", sinon "SURVEILLANCE". Afficher aussi le nombre d’anomalies.',tests:[{expected:'Anomalies = 2\nPANNE PROBABLE'}]},

  {id:'tp8q1',tp:'TP8',title:'Q1 — Écrire un fichier',description:'Créer le fichier mesures.txt et y écrire trois lignes : 5.0, 5.1 et 4.9. Puis afficher "Fichier créé".',tests:[{expected:'Fichier créé'}]},
  {id:'tp8q2',tp:'TP8',title:'Q2 — Lire un fichier',description:'Créer mesures.txt contenant 5.0, 5.1 et 4.9 (une valeur par ligne), puis le relire et afficher son contenu avec print(..., end="").',tests:[{expected:'5.0\n5.1\n4.9'}]},
  {id:'tp8q3',tp:'TP8',title:'Q3 — Exploiter les lignes',description:'Créer mesures.txt avec 4.8, 5.2, 5.0. Relire les lignes, convertir les valeurs en float et afficher leur moyenne.\n\nSortie attendue :\nMoyenne = 5.0 V',tests:[{expected:'Moyenne = 5.0 V'}]},
  {id:'tp8q4',tp:'TP8',title:'Q4 — CSV simple',description:'Créer mesures.csv contenant exactement :\ntemps,tension\n0,5.0\n1,5.1\n2,4.9\nPuis afficher "CSV prêt".',tests:[{expected:'CSV prêt'}]},
  {id:'tp8q5',tp:'TP8',title:'Q5 — Analyser un CSV',description:'Créer mesures.csv avec l’en-tête temps,tension et les tensions 5.0, 6.4, 5.2. Relire le fichier (sans compter l’en-tête) et afficher le nombre de tensions > 6 V.\n\nSortie attendue :\nAlertes = 1',tests:[{expected:'Alertes = 1'}]},

  {id:'tp9q1',tp:'TP9',title:'Q1 — Statistiques',description:'Pour [18.2, 19.1, 20.4, 21.0, 22.3], afficher min, max et moyenne arrondie à 2 décimales.',tests:[{expected:'Min = 18.2\nMax = 22.3\nMoyenne = 20.2'}]},
  {id:'tp9q2',tp:'TP9',title:'Q2 — Écarts à la consigne',description:'La consigne vaut 20 °C. Pour [18, 20, 23, 19], afficher les écarts mesure-consigne, un par ligne.',tests:[{expected:'-2\n0\n3\n-1'}]},
  {id:'tp9q3',tp:'TP9',title:'Q3 — Pourcentage conforme',description:'Pour [4.9, 5.0, 5.2, 6.0, 5.1], une mesure est conforme entre 4.5 et 5.5 V inclus. Afficher le pourcentage de mesures conformes.\n\nSortie attendue :\n80.0 %',tests:[{expected:'80.0 %'}]},
  {id:'tp9q4',tp:'TP9',title:'Q4 — Barres ASCII',description:'Pour mesures=[2,4,1,3], afficher un mini-graphique avec # :\n1: ##\n2: ####\n3: #\n4: ###',tests:[{expected:'1: ##\n2: ####\n3: #\n4: ###'}]},
  {id:'tp9q5',tp:'TP9',title:'Q5 — Tableau de bord',description:'Pour [4.8, 5.0, 5.2, 6.3, 4.7], afficher le nombre de mesures, la moyenne arrondie à 2 décimales et le nombre de valeurs >6 V.\n\nSortie attendue :\nMesures = 5\nMoyenne = 5.2 V\nAlertes = 1',tests:[{expected:'Mesures = 5\nMoyenne = 5.2 V\nAlertes = 1'}]},

  {id:'tp10q1',tp:'TP10',title:'Étape 1 — Acquisition',description:'PROJET CIEL — Surveillance d’une alimentation. Créer tensions=[5.0,5.1,6.4,4.8,5.2] et temperatures=[21,22,23,29,24]. Afficher le nombre de relevés.\n\nSortie attendue :\n5 relevés',tests:[{expected:'5 relevés'}]},
  {id:'tp10q2',tp:'TP10',title:'Étape 2 — Fonction de contrôle',description:'PROJET CIEL — Écrire controle_tension(U) qui retourne "OK" pour 4.5 <= U <= 5.5 et "ALERTE" sinon. Tester 5.0 puis 6.4.',tests:[{expected:'OK\nALERTE'}]},
  {id:'tp10q3',tp:'TP10',title:'Étape 3 — Analyse des capteurs',description:'PROJET CIEL — Pour tensions=[5.0,5.1,6.4,4.8,5.2] et temperatures=[21,22,23,29,24], compter les tensions hors [4.5;5.5] et les températures >25.\n\nSortie attendue :\nAlertes tension = 1\nAlertes température = 1',tests:[{expected:'Alertes tension = 1\nAlertes température = 1'}]},
  {id:'tp10q4',tp:'TP10',title:'Étape 4 — Journal de diagnostic',description:'PROJET CIEL — Créer diagnostic.txt contenant exactement :\nTension: 1 alerte\nTemperature: 1 alerte\nPuis afficher "Diagnostic enregistré".',tests:[{expected:'Diagnostic enregistré'}]},
  {id:'tp10q5',tp:'TP10',title:'Étape 5 — Bilan final',description:'PROJET CIEL — Avec 1 alerte tension et 1 alerte température, afficher un bilan final. Si au moins une alerte existe, l’état est "MAINTENANCE REQUISE".\n\nSortie attendue :\n=== BILAN CIEL ===\nAlertes = 2\nÉtat = MAINTENANCE REQUISE',tests:[{expected:'=== BILAN CIEL ===\nAlertes = 2\nÉtat = MAINTENANCE REQUISE'}]}

];
